# Generated by Django 3.0.4 on 2020-03-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
