# Generated by Django 3.0.4 on 2020-03-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
