# Generated by Django 3.0.4 on 2020-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_ability_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='double_damage_from',
            field=models.CharField(choices=[('normal', 'Normal'), ('fighting', 'Fighting'), ('flying', 'Flying'), ('poison', 'Poison'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('steel', 'Steel'), ('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('fairy', 'Fairy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='half_damage_from',
            field=models.CharField(choices=[('normal', 'Normal'), ('fighting', 'Fighting'), ('flying', 'Flying'), ('poison', 'Poison'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('steel', 'Steel'), ('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('fairy', 'Fairy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='no_damage_from',
            field=models.CharField(choices=[('normal', 'Normal'), ('fighting', 'Fighting'), ('flying', 'Flying'), ('poison', 'Poison'), ('ground', 'Ground'), ('rock', 'Rock'), ('bug', 'Bug'), ('ghost', 'Ghost'), ('steel', 'Steel'), ('fire', 'Fire'), ('water', 'Water'), ('grass', 'Grass'), ('electric', 'Electric'), ('psychic', 'Psychic'), ('ice', 'Ice'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('fairy', 'Fairy')], max_length=100, null=True),
        ),
    ]
