# Generated by Django 3.0.4 on 2020-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_auto_20200311_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='double_damage_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='half_damage_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='no_damage_from',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
